language: node_js
node_js:
  - node
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
notifications:
  email: false
